/**
 * GitHub PR creation for automated fix PRs.
 * Uses `gh` CLI (GitHub CLI) to create branches and PRs.
 *
 * Security: All commands use execFile with argument arrays (no shell interpolation).
 */
import { safeExec } from '../../utils/shell.js';
import * as logger from '../../utils/logger.js';
import type { AppliedFix } from './lockfile-writer.js';

export type PrResult = {
  success: boolean;
  prUrl?: string;
  error?: string;
};

/**
 * Create a GitHub PR with the applied fixes.
 * Requires `gh` CLI to be installed and authenticated.
 */
export async function createFixPr(
  projectDir: string,
  fixes: AppliedFix[],
): Promise<PrResult> {
  // Check gh is available
  const ghCheck = await safeExec('gh', ['--version'], { cwd: projectDir, timeout: 10_000 });
  if (ghCheck.exitCode !== 0) {
    return { success: false, error: 'GitHub CLI (gh) is not installed. Install from https://cli.github.com/' };
  }

  // Check auth
  const authCheck = await safeExec('gh', ['auth', 'status'], { cwd: projectDir, timeout: 10_000 });
  if (authCheck.exitCode !== 0) {
    return { success: false, error: 'GitHub CLI is not authenticated. Run `gh auth login` first.' };
  }

  const branchName = `auditfix/security-updates-${Date.now()}`;
  const fixSummary = fixes.map((f) => `- ${f.packageName}: ${f.from} → ${f.to}`).join('\n');

  // Create branch
  const branchResult = await safeExec('git', ['checkout', '-b', branchName], {
    cwd: projectDir,
    timeout: 10_000,
  });
  if (branchResult.exitCode !== 0) {
    return { success: false, error: `Failed to create branch: ${branchResult.stderr}` };
  }

  // Stage and commit changes
  const addResult = await safeExec('git', ['add', 'package.json', 'package-lock.json', 'yarn.lock', 'pnpm-lock.yaml'], {
    cwd: projectDir,
    timeout: 10_000,
  });

  const commitResult = await safeExec('git', ['commit', '-m', `fix: update ${fixes.length} vulnerable dependencies\n\n${fixSummary}`], {
    cwd: projectDir,
    timeout: 10_000,
  });
  if (commitResult.exitCode !== 0) {
    // Restore original branch
    await safeExec('git', ['checkout', '-'], { cwd: projectDir, timeout: 10_000 });
    return { success: false, error: `Failed to commit: ${commitResult.stderr}` };
  }

  // Push branch
  const pushResult = await safeExec('git', ['push', '-u', 'origin', branchName], {
    cwd: projectDir,
    timeout: 30_000,
  });
  if (pushResult.exitCode !== 0) {
    return { success: false, error: `Failed to push: ${pushResult.stderr}` };
  }

  // Create PR
  const title = `fix: update ${fixes.length} vulnerable dependencies`;
  const body = `## Security Updates\n\nAutomatically generated by [auditfix](https://www.npmjs.com/package/auditfix).\n\n### Changes\n\n${fixSummary}\n\n---\n*Run \`npx auditfix\` to verify these fixes.*`;

  const prResult = await safeExec('gh', ['pr', 'create', '--title', title, '--body', body], {
    cwd: projectDir,
    timeout: 30_000,
  });

  if (prResult.exitCode !== 0) {
    return { success: false, error: `Failed to create PR: ${prResult.stderr}` };
  }

  const prUrl = prResult.stdout.trim();
  logger.info(`Created PR: ${prUrl}`);

  // Switch back to original branch
  await safeExec('git', ['checkout', '-'], { cwd: projectDir, timeout: 10_000 });

  return { success: true, prUrl };
}
