import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { detectAndParseLockfile } from '../../src/core/lockfile/parser.js';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';

/**
 * Helper to create a temp directory for each test.
 */
function makeTempDir(): string {
  return fs.mkdtempSync(path.join(os.tmpdir(), 'auditfix-parser-test-'));
}

function cleanupDir(dir: string): void {
  fs.rmSync(dir, { recursive: true, force: true });
}

/**
 * Minimal valid package-lock.json (npm v2/v3 format).
 */
function writeNpmLockfile(dir: string): void {
  const lockfile = {
    name: 'test-project',
    version: '1.0.0',
    lockfileVersion: 3,
    packages: {
      '': {
        name: 'test-project',
        version: '1.0.0',
        dependencies: {
          'lodash': '^4.17.21',
        },
      },
      'node_modules/lodash': {
        version: '4.17.21',
        resolved: 'https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz',
        integrity: 'sha512-fake',
      },
    },
  };
  fs.writeFileSync(path.join(dir, 'package-lock.json'), JSON.stringify(lockfile, null, 2));
}

/**
 * Minimal valid yarn.lock (classic format).
 */
function writeYarnClassicLockfile(dir: string): void {
  const content = `# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
# yarn lockfile v1


lodash@^4.17.21:
  version "4.17.21"
  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz"
  integrity sha512-fake
`;
  fs.writeFileSync(path.join(dir, 'yarn.lock'), content);
  // Yarn parser needs package.json manifest
  const manifest = {
    name: 'test-project',
    version: '1.0.0',
    dependencies: { lodash: '^4.17.21' },
  };
  fs.writeFileSync(path.join(dir, 'package.json'), JSON.stringify(manifest, null, 2));
}

/**
 * Minimal valid pnpm-lock.yaml (v9 format).
 */
function writePnpmLockfile(dir: string): void {
  const content = `lockfileVersion: '9.0'

settings:
  autoInstallPeers: true
  excludeLinksFromLockfile: false

importers:
  .:
    dependencies:
      lodash:
        specifier: ^4.17.21
        version: 4.17.21

packages:
  lodash@4.17.21:
    resolution: {integrity: sha512-fake}

snapshots:
  lodash@4.17.21: {}
`;
  fs.writeFileSync(path.join(dir, 'pnpm-lock.yaml'), content);
}

describe('detectAndParseLockfile', () => {
  let tmpDir: string;

  beforeEach(() => {
    tmpDir = makeTempDir();
  });

  afterEach(() => {
    cleanupDir(tmpDir);
  });

  describe('lockfile detection', () => {
    it('detects package-lock.json and routes to npm parser', () => {
      writeNpmLockfile(tmpDir);

      const result = detectAndParseLockfile(tmpDir);

      expect(result.type).toMatch(/^npm/);
      expect(result.graph).toBeInstanceOf(Map);
      expect(result.packageCount).toBeGreaterThanOrEqual(1);
    });

    it('detects yarn.lock and routes to yarn parser', () => {
      writeYarnClassicLockfile(tmpDir);

      const result = detectAndParseLockfile(tmpDir);

      expect(result.type).toBe('yarn-classic');
      expect(result.graph).toBeInstanceOf(Map);
    });

    it('detects pnpm-lock.yaml and routes to pnpm parser', () => {
      writePnpmLockfile(tmpDir);

      const result = detectAndParseLockfile(tmpDir);

      expect(result.type).toMatch(/^pnpm/);
      expect(result.graph).toBeInstanceOf(Map);
    });
  });

  describe('priority when multiple lockfiles exist', () => {
    it('prefers package-lock.json over yarn.lock', () => {
      writeNpmLockfile(tmpDir);
      writeYarnClassicLockfile(tmpDir);

      const result = detectAndParseLockfile(tmpDir);

      expect(result.type).toMatch(/^npm/);
    });

    it('prefers package-lock.json over pnpm-lock.yaml', () => {
      writeNpmLockfile(tmpDir);
      writePnpmLockfile(tmpDir);

      const result = detectAndParseLockfile(tmpDir);

      expect(result.type).toMatch(/^npm/);
    });

    it('prefers yarn.lock over pnpm-lock.yaml', () => {
      writeYarnClassicLockfile(tmpDir);
      writePnpmLockfile(tmpDir);

      const result = detectAndParseLockfile(tmpDir);

      expect(result.type).toBe('yarn-classic');
    });
  });

  describe('error cases', () => {
    it('throws when no lockfile is found', () => {
      expect(() => detectAndParseLockfile(tmpDir)).toThrow(
        /No lockfile found/,
      );
    });

    it('throws for an invalid/non-existent directory', () => {
      const bogusDir = path.join(tmpDir, 'does-not-exist');

      expect(() => detectAndParseLockfile(bogusDir)).toThrow();
    });

    it('throws when lockfile is empty', () => {
      fs.writeFileSync(path.join(tmpDir, 'package-lock.json'), '');

      expect(() => detectAndParseLockfile(tmpDir)).toThrow(
        /empty/i,
      );
    });

    it('throws when lockfile contains only whitespace', () => {
      fs.writeFileSync(path.join(tmpDir, 'package-lock.json'), '   \n  \t  ');

      expect(() => detectAndParseLockfile(tmpDir)).toThrow(
        /empty/i,
      );
    });
  });

  describe('parsed result shape', () => {
    it('returns the expected LockfileParseResult fields', () => {
      writeNpmLockfile(tmpDir);

      const result = detectAndParseLockfile(tmpDir);

      expect(result).toHaveProperty('type');
      expect(result).toHaveProperty('graph');
      expect(result).toHaveProperty('packageCount');
      expect(result).toHaveProperty('skipped');
      expect(Array.isArray(result.skipped)).toBe(true);
      expect(typeof result.packageCount).toBe('number');
    });

    it('packageCount equals graph.size', () => {
      writeNpmLockfile(tmpDir);

      const result = detectAndParseLockfile(tmpDir);

      expect(result.packageCount).toBe(result.graph.size);
    });
  });
});
